language: cpp
os: linux
dist: trusty
compiler: gcc
sudo: required

before_install: ./travis_before_install.sh
before_script: ./travis_before_script.sh
script: mkdir build && cd build && cmake .. && make VERBOSE=1 && make test

