language: cpp
os: linux
dist: trusty
compiler: gcc
sudo: required
services: 
  - postgresql

before_install: ./travis_before_install.sh
before_script: 
  - sudo ./travis_before_script.sh
  
script: mkdir build && cd build && cmake .. && make VERBOSE=1 && make test CTEST_OUTPUT_ON_FAILURE=TRUE

